name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore HelloWorldApp

    - name: Build
      run: dotnet build HelloWorldApp --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
